# Generated by Django 3.0.8 on 2021-06-03 12:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=32, null=True)),
                ('lastname', models.CharField(blank=True, max_length=32, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True, max_length=1024, null=True)),
                ('birth_date', models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1984), users.models.max_value_current_year])),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('follow_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=255, null=True)),
                ('degree', models.CharField(choices=[('BE', 'B.Tech'), ('DC', 'Diploma'), ('IM', 'Intermediate'), ('HS', 'High School')], default='BE', max_length=3)),
                ('field', models.CharField(choices=[('CS', 'Computer Science & Engineering'), ('CE', 'Civil Engineering'), ('EC', 'Electronics and Communication'), ('ME', 'Mechanical Engineering'), ('AS', 'Applied Science'), ('PCM', 'Mathematics Major')], default='AS', max_length=3)),
                ('startYear', models.IntegerField(validators=[django.core.validators.MinValueValidator(users.models.Profile.birthyear), users.models.max_value_current_year], verbose_name='year')),
                ('endYear', models.IntegerField(validators=[django.core.validators.MinValueValidator(users.models.Profile.birthyear), users.models.max_value_current_year], verbose_name='year')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MaxValueValidator(100)])),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('organization', models.CharField(max_length=255, null=True)),
                ('expire', models.BooleanField(default=False)),
                ('issueDate', models.IntegerField(validators=[django.core.validators.MinValueValidator(users.models.Profile.birthyear), users.models.max_value_current_year], verbose_name='year')),
                ('expirationDate', models.IntegerField(validators=[django.core.validators.MinValueValidator(users.models.Profile.birthyear)], verbose_name='year')),
                ('credentialID', models.CharField(blank=True, max_length=32, null=True)),
                ('credentialURL', models.URLField(blank=True)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
