# Generated by Django 3.0.8 on 2021-06-04 09:36

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='endYear',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(users.models.Profile.birthyear), users.models.max_value_current_year], verbose_name='endyear'),
        ),
        migrations.AlterField(
            model_name='education',
            name='startYear',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(users.models.Profile.birthyear), users.models.max_value_current_year], verbose_name='startyear'),
        ),
    ]
