# Generated by Django 3.0.8 on 2021-06-04 11:35

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210604_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='expirationDate',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1984)], verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='issueDate',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1984), users.models.max_value_current_year], verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='education',
            name='endYear',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1984), users.models.max_value_current_year], verbose_name='endyear'),
        ),
        migrations.AlterField(
            model_name='education',
            name='startYear',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1984), users.models.max_value_current_year], verbose_name='startyear'),
        ),
    ]
