# Generated by Django 3.0.8 on 2021-06-06 03:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210604_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='expirationDate',
            field=models.DateField(default=datetime.date(2021, 6, 6)),
        ),
        migrations.AlterField(
            model_name='certification',
            name='issueDate',
            field=models.DateField(default=datetime.date(2021, 6, 6)),
        ),
    ]
