# Generated by Django 3.0.8 on 2021-06-06 18:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='semester')),
                ('evenOdd', models.CharField(max_length=7)),
                ('totalSub', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)], verbose_name='totalsubjects')),
                ('theorySub', models.IntegerField()),
                ('practicalSub', models.IntegerField()),
                ('totalMarksObtained', models.IntegerField()),
                ('totalMarks', models.IntegerField()),
                ('carryOverSub', models.IntegerField()),
                ('sgpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
