# Generated by Django 3.0.8 on 2021-06-07 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='issueDate',
            field=models.DateField(default=datetime.date(2021, 6, 7)),
        ),
        migrations.AlterField(
            model_name='project',
            name='startDate',
            field=models.DateField(default=datetime.date(2021, 6, 7)),
        ),
    ]
