# Generated by Django 3.0.8 on 2021-06-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210608_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('B.Tech', 'B.Tech'), ('Diploma', 'Diploma'), ('Intermediate', 'Intermediate'), ('High School', 'High School')], default='B.Tech', max_length=15),
        ),
        migrations.AlterField(
            model_name='education',
            name='field',
            field=models.CharField(choices=[('Computer Science & Engineering', 'Computer Science & Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Electronics and Communication', 'Electronics and Communication'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Applied Science', 'Applied Science'), ('Mathematics Major', 'Mathematics Major')], default='Applied Science', max_length=30),
        ),
    ]
