# Generated by Django 3.0.8 on 2021-06-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210609_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='extraskills',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='techskills',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
