# Generated by Django 3.0.8 on 2021-06-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210609_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rollno',
            field=models.IntegerField(null=True),
        ),
    ]
