# Generated by Django 3.0.8 on 2021-06-13 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210613_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='usertype',
        ),
    ]
