# Generated by Django 3.0.8 on 2021-06-13 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_profile_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='usertype',
        ),
    ]
