# Generated by Django 3.0.8 on 2021-06-21 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20210621_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='issueDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='project',
            name='startDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
