# Generated by Django 3.0.8 on 2021-06-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20210621_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='certificatePDF',
            field=models.FileField(null=True, upload_to='uploads/pdf_files'),
        ),
    ]
