# Generated by Django 3.0.8 on 2021-06-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_attachedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attachedimage',
            field=models.ImageField(blank=True, upload_to='uploads/post_photos'),
        ),
    ]
