# Generated by Django 3.0.8 on 2021-06-10 05:08

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210610_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attachedimage',
            field=models.ImageField(blank=True, upload_to=blog.models.get_file_path),
        ),
    ]
