# Generated by Django 3.0.8 on 2021-06-23 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_messagemodel_threadmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threadmodel',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='threadmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='MessageModel',
        ),
        migrations.DeleteModel(
            name='ThreadModel',
        ),
    ]
